// constants/components-theme.ts
export const shadcn = {
  colors: {
    background: "#000000",
    foreground: "#fafafa",
    card: "#171717",
    cardForeground: "#fafafa",
    popover: "#171717",
    popoverForeground: "#fafafa",
    primary: "#fafafa",
    primaryForeground: "#0a0a0a",
    secondary: "#262626",
    secondaryForeground: "#fafafa",
    muted: "#262626",
    mutedForeground: "#a3a3a3",
    accent: "#262626",
    accentForeground: "#fafafa",
    destructive: "#7f1d1d",
    destructiveForeground: "#fecaca",
    border: "#262626",
    input: "#262626",
    ring: "#d4d4d4",
    success: "#14532d",
    successForeground: "#bbf7d0",
    warning: "#713f12",
    warningForeground: "#fef08a",
    brand: "#fafafa",
    brandForeground: "#000000",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
  },
  radius: {
    sm: 6,
    md: 8,
    lg: 12,
    xl: 16,
    full: 9999,
  },
  typography: {
    title: { fontSize: 34, fontWeight: "700" as const, letterSpacing: -0.5 },
    sectionHeader: {
      fontSize: 13,
      fontWeight: "600" as const,
      letterSpacing: 0.5,
      textTransform: "uppercase" as const,
    },
    body: { fontSize: 16, fontWeight: "500" as const },
    bodySmall: { fontSize: 14, fontWeight: "500" as const },
    caption: { fontSize: 12, fontWeight: "400" as const },
  },
};
